### ISSUE TITLE
无法弹出软键盘的原因已找到

### ISSUE THREAD

**Issue by limuyang2** [showzeng/PureComment#1]
我多次尝试打印了整个DialogFragment的生命周期后，理清楚了顺序。启动顺序大致如下：
 onCreate
onCreateDialog
onActivityCreated
onStart
而弹出软键盘的方法是在onCreateDialog中执行的。在生命周期的启动过程中，view是并未绘制完成的（事实证明也是如此，我在onStart中调用弹出键盘方法也无效），当然就拿不到焦点。
设置延迟弹出键盘，其实就是在等view绘制。但是设置延迟是很不好，因为不同设备的绘制时间不一样，导致延迟的设置不准确。

既然知道了是view绘制滞后的问题，那么就可以在EditText中设置一个监听事件，当它被绘制好以后，弹出键盘即可。

在onCreateDialog()方法中，拿到到EditText后，设置如下代码即可：
`
commentEditText.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                Log.i("commentEditText","onGlobalLayout");
                InputMethodManager imm = (InputMethodManager) getActivity().getSystemService(getActivity().INPUT_METHOD_SERVICE);
                imm.showSoftInput(commentEditText, 0);
            }
        });
`

**Comment by limuyang2** [comment]
回复里代码显示好乱，我提交个文件吧

**Comment by ZoeyWoohoo** [comment]
@limuyang2 感谢！

确实，又回头看了一下 Fragment 和 DialogFragment 的生命周期，的确是绘制的问题，onStart() 方法中也只是开始绘制时调用，并不知道具体绘制结束的时间。但是这里还是有个小 bug，监听器监听的是视图的变化，在你按下软键盘中的收起键盘按键或者返回键时，由于监听器的作用，软键盘将不会被收起，即收起之后立马又被呼出。

软键盘呼出后注销监听器就可以了。

**Comment by limuyang2** [comment]
是的，我也发现这个bug了，我用了全局bool变量来进行判断，就不会收起再弹出了

发自我的 iPhone

在 2017年12月21日，23:03，showzeng <notifications@github.com<mailto:notifications@github.com>> 写道：


感谢！

确实，又回头看了一下 Fragment 和 DialogFragment 的生命周期，的确是绘制的问题，onStart() 方法中也只是开始绘制时调用，并不知道具体绘制结束的时间。但是这里还是有个小 bug，监听器监听的是视图的变化，在你按下软键盘中的收起键盘按键或者返回键时，由于监听器的作用，软键盘将不会被收起，即收起之后立马又被呼出。

软键盘呼出后注销监听器就可以了。

**Comment by ZoeyWoohoo** [comment]
@limuyang2 [文章](https://showzeng.itscoder.com/android/2017/08/11/the-imitation-of-the-international-weibo-comment-box)已更新，再次感谢！
