### ISSUE TITLE
发送评论后，软键盘无法自动隐藏

### ISSUE THREAD

**Issue by EpicWang** [showzeng/PureComment#4]
如题，使用以下方法也无效
![tim 20180720180842](https://user-images.githubusercontent.com/15323264/42997194-6cce678a-8c48-11e8-8901-171354a61822.png)
![tim 20180720181057](https://user-images.githubusercontent.com/15323264/42997195-6f0d9aa2-8c48-11e8-8f88-cf3b3314c1d1.png)

**Comment by ZoeyWoohoo** [comment]
@EpicWang 能说的再具体一点吗？机型？版本？

**Comment by ZoeyWoohoo** [comment]
发送评论后调用了 `dismiss()` 方法，DialogFragment 已经消失了，此时也失去了焦点，软键盘应该会自动隐藏的。

**Comment by ZoeyWoohoo** [comment]
你调用你的 `closeKeyboard()` 方法是在 `dismiss()` 方法之前还是之后？Dismiss 之后就不存在 EditText 了。

**Comment by EpicWang** [comment]
@showzeng 抱歉，昨天是有点多，没看到回复。
这是测试机型：
![screenshot_2018-07-21-09-49-51](https://user-images.githubusercontent.com/15323264/43031022-d7bf2e0c-8ccb-11e8-96e0-cabe31930ecd.png)

现在的问题是：
弹出评论框，1：点击外部，评论框消失，2：发送评论后，评论框自动消失。
以上2种情况，软键盘都不会自动消失。

我的解决方式如下，但是很遗憾，无效。
`public void onDismiss(DialogInterface dialog) {
        dataCallback.setCommentText(commentEditText.getText().toString());
        if (inputMethodManager != null) { 
 inputMethodManager.hideSoftInputFromWindow(getActivity().getWindow().getDecorView().getWindowToken(), 0);
        }
        super.onDismiss(dialog);
    }
`

**Comment by EpicWang** [comment]
我目前的解决方式如下：
1、禁止外部点击消失
2、在发送之后，调用closeKeybord();

![tim 20180721102243](https://user-images.githubusercontent.com/15323264/43031235-29715f96-8cd0-11e8-9f4a-5e635af6f0a0.png)
![tim 20180721102020](https://user-images.githubusercontent.com/15323264/43031237-2d7475c4-8cd0-11e8-8838-ff79972087b1.png)

**Comment by ZoeyWoohoo** [comment]
初步分析可能有部分机型，在失去焦点本该收起软键盘却没有收起。外部取消所调用的方法是 `onCancel()`，你只在 `onDismiss()` 里手动收起软键盘，外部取消事件仍然是无效的。

再者就是这个机子手动收起软键盘有效吗？或者说你目前的解决方案是有效的吗？如果是有效的，我推荐如下方案：

1.外部点击取消开启
2.在 `onDismiss()` 和 `onCancel()` 中手动收起软键盘，即调用你的 `closeKeyboard()` 方法

``` java
@Override
public void onDismiss(DialogInterface dialog) {
    dataCallback.setCommentText(commentEditText.getText().toString());
    KeyBoardUtils.closeKeyboard(commentEditText, getActivity());
    super.onDismiss(dialog);
}

@Override
public void onCancel(DialogInterface dialog) {
    dataCallback.setCommentText(commentEditText.getText().toString());
    KeyBoardUtils.closeKeyboard(commentEditText, getActivity());
    super.onCancel(dialog);
}
```

**Comment by EpicWang** [comment]
@showzeng 感谢回复！
目前先用这种方式解决，等有时间在研究下。
Enjoy！
